%% Pipeline_toGenerate_8subvolumeData_and_combineSeparateAnalysisResults
%
% Author: Jungsik Noh, UTSW, Dallas, TX  


%% 1. Generate 8 sub-volume movieData
%
% Input is a movieData object (MD) for original time-lapse 3D images that are
% too big to analyze in a single batch.
% The volume is divided into 8 sub-volumes, where we can specify the ratio
% of the edge length of the sub-volume to the edge of the full-volume. Some
% degree of overlaps between sub-volumes is recommended by setting the
% ratioSubVolumeEdge > 0.5.

generate_8SubVolumes(MD, 'ratioSubVolumeEdge', 0.6)


%% 2. Run Pipeline_JNT.m with each movieData for the sub-volumes.


%% 3. Combine separate results for the sub-volumes to make the result for the original movieData
%
% First load 'param_generate_8SubVolumes.mat' generated by
% generate_8SubVolumes() in the movieData output directory.
% Also load the original MD (movieData) object.
% The option of par4.activityWeightedByImgCorr needs to be specified here 
% because the corresponding output folder name is different.

activityWeightedByImgCorr = true;       
combineOutput_8SubVolumes(MD, param_generate_8SubVolumes, activityWeightedByImgCorr)

%% End